// Meta (Facebook) Pixel #2 — dedicated SOLELY to form-submission / Lead
// conversion tracking, for the digital marketing team. Completely separate
// from the website-interaction pixel in metaPixel.js:
//   - never fires PageView
//   - never initializes eagerly on page load (only lazily, on the first
//     confirmed successful submission)
//   - only ever sends the Meta standard "Lead" event, scoped to THIS pixel
//     alone via fbq('trackSingle', ...) so it can never piggyback on (or be
//     piggybacked by) the main pixel's plain fbq('track', ...) calls
//
// Pixel ID comes from REACT_APP_FORM_SUBMISSION_PIXEL_ID only; if it's
// unset, tracking is a no-op — no fake/placeholder ID is ever used.
import { loadPixelScript } from "./metaPixel";

const PIXEL_ID = process.env.REACT_APP_FORM_SUBMISSION_PIXEL_ID;

let initialized = false;
let lastSubmissionId = null;

function ensureInitialized() {
  if (initialized) return true;
  if (!PIXEL_ID || typeof window === "undefined") return false;
  loadPixelScript();
  window.fbq("init", PIXEL_ID);
  initialized = true;
  return true;
}

// Call exactly once, right after the existing enquiry API has confirmed a
// submission actually succeeded (never on popup-open, submit-click,
// validation failure, or a failed/erroring request).
//
// `submissionId` should be a fresh value generated by the caller for that
// one submit attempt (e.g. `${Date.now()}-${Math.random()}`). Re-invoking
// with the same id (a re-render, React StrictMode's double-invoke, an
// accidental duplicate call) is ignored, so a single successful submission
// can only ever produce one Lead event. Contains no PII — it's just a
// dedupe token, never sent to Meta.
export function trackFormSubmission(submissionId, formName) {
  if (!submissionId || submissionId === lastSubmissionId) return;
  if (!ensureInitialized() || !window.fbq) return;
  lastSubmissionId = submissionId;
  window.fbq("trackSingle", PIXEL_ID, "Lead", formName ? { content_name: formName } : undefined);
}

export const trackLeadConversion = trackFormSubmission;
