// Student Plan PPT -- slide construction.
//
// Consumes ONLY the already-normalized model from ./pptNormalize.js (never
// the raw planner payload, never re-derives/recalculates anything) and
// produces a real, editable .pptx via pptxgenjs, styled entirely through
// ./pptDesignSystem.js's shared primitives -- no per-slide one-off styling.
// Zero network calls, zero filesystem writes -- the buffer is built
// entirely in memory (pptx.write({ outputType: "nodebuffer" })).
//
// IVYHUTS has no logo image asset (SiteNavbar.js renders a two-tone
// "IVY"/"huts" text wordmark, not an <img>), so every slide reproduces that
// same text wordmark instead of introducing a new image dependency.
"use strict";

const PptxGenJS = require("pptxgenjs");
const DS = require("./pptDesignSystem");

const { COLORS, FONT, TYPE, PAGE_W, PAGE_H, MARGIN, CONTENT_W, CONTENT_TOP, CONTENT_BOTTOM, CONTENT_H, GUTTER, RADIUS_CARD, CARD_LINE, truncate } = DS;

const MATCH_TONE = {
    "Strong Match": { fill: COLORS.success, tier: 3 },
    "Good Match": { fill: COLORS.purple, tier: 2 },
    "Possible Path": { fill: COLORS.warning, tier: 1 },
};

function matchTone(label) {
    return MATCH_TONE[label] || { fill: COLORS.purple, tier: 2 };
}

// A qualitative (not fabricated-numeric) strength bar: pptNormalize.js only
// ever exposes a career's matchLabel ("Strong Match" / "Good Match" /
// "Possible Path"), never its underlying numeric matchScore -- so this bar's
// fill reflects that same three-tier category, with no invented percentage
// text overlaid on it. (Residences DO carry a real numeric matchScore from
// accommodationIndex.js's own ranking -- see buildComparisonSlide below,
// which uses that real number directly.)
function qualitativeBar(slide, { x, y, w, h = 0.12, label }) {
    const { fill, tier } = matchTone(label);
    DS.progressBar(slide, { x, y, w, h, value: tier, max: 3, fillColor: fill });
}

// ---- Slide 1: Cover ----
function buildCoverSlide(pptx, n) {
    const slide = pptx.addSlide();
    slide.background = { color: COLORS.purpleDeep };

    slide.addText(
        [{ text: "IVY", options: { color: COLORS.white, bold: true } }, { text: "huts", options: { color: COLORS.goldLight, bold: true } }],
        { x: MARGIN, y: 0.55, w: 3, h: 0.4, fontSize: 18, fontFace: FONT }
    );

    const leftW = 6.9;
    slide.addText("STUDENT PLAN", { x: MARGIN, y: 1.55, w: leftW, h: 0.32, fontSize: TYPE.coverLabel, bold: true, color: COLORS.gold, charSpacing: 2.5, fontFace: FONT });
    slide.addText("YOUR JOURNEY\nFROM HOUSING\nTO HIRING", {
        x: MARGIN, y: 1.95, w: leftW, h: 2.0, fontSize: TYPE.coverTitle, bold: true, color: COLORS.white, fontFace: FONT, lineSpacingMultiple: 1.04,
    });
    slide.addShape("line", { x: MARGIN, y: 4.05, w: 0.7, h: 0, line: { color: COLORS.gold, width: 3 } });

    const infoRows = [];
    if (n.university.available) infoRows.push(["University", n.university.name]);
    if (n.student.degree) infoRows.push(["Degree", [n.student.degree, n.student.specialization].filter(Boolean).join(" -- ")]);
    if (n.student.name) infoRows.unshift(["Student", n.student.name]);
    infoRows.forEach(([label, value], i) => {
        const y = 4.35 + i * 0.72;
        slide.addText(label.toUpperCase(), { x: MARGIN, y, w: leftW, h: 0.26, fontSize: 10.5, bold: true, color: COLORS.gold, charSpacing: 1.2, fontFace: FONT });
        slide.addText(truncate(value, 70), { x: MARGIN, y: y + 0.27, w: leftW, h: 0.4, fontSize: 17, bold: true, color: COLORS.white, fontFace: FONT });
    });

    // Right: abstract vertical journey visual (Housing -> University -> Career) --
    // no map, no stock imagery, purely a connected-nodes representation.
    const rightX = 8.5;
    const rightW = PAGE_W - MARGIN - rightX;
    ["Housing", "University", "Career"].forEach((label, i) => {
        const y = 2.5 + i * 1.45;
        DS.numberBadge(slide, { x: rightX, y, d: 0.56, text: i + 1, fill: i === 2 ? COLORS.gold : COLORS.rose, textColor: COLORS.purpleDeep, fontSize: 16 });
        slide.addText(label.toUpperCase(), { x: rightX + 0.76, y: y + 0.08, w: rightW - 0.76, h: 0.4, fontSize: 15, bold: true, color: COLORS.white, fontFace: FONT, valign: "middle" });
        if (i < 2) slide.addShape("line", { x: rightX + 0.28, y: y + 0.56, w: 0, h: 0.89, line: { color: "6E4E7E", width: 2 } });
    });

    slide.addText(
        "Generated by IVYHUTS. Estimates and planning guidance only -- not a guarantee of admission, housing, salary or employment.",
        { x: MARGIN, y: PAGE_H - 0.55, w: 12.1, h: 0.4, fontSize: 9, color: "9C82A0", fontFace: FONT }
    );
    return slide;
}

// ---- Slide: Your Study Destination ----
function buildUniversitySlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "University", title: "Your Study Destination" });
    const u = n.university;
    const leftW = 6.9;

    slide.addText(u.name, { x: MARGIN, y: CONTENT_TOP, w: leftW, h: 0.55, fontSize: 24, bold: true, color: COLORS.ink, fontFace: FONT });
    const location = [u.city, u.country].filter(Boolean).join(", ");
    if (location) slide.addText(location.toUpperCase(), { x: MARGIN, y: CONTENT_TOP + 0.56, w: leftW, h: 0.3, fontSize: 12, bold: true, color: COLORS.rose, charSpacing: 1, fontFace: FONT });
    if (u.summary) {
        slide.addText(truncate(u.summary, 320), {
            x: MARGIN, y: CONTENT_TOP + 0.98, w: leftW, h: 1.5, fontSize: TYPE.body, color: COLORS.inkSoft, fontFace: FONT, lineSpacingMultiple: 1.35, valign: "top",
        });
    }
    if (u.keyFacts.length > 0) {
        DS.infoCard(slide, { x: MARGIN, y: CONTENT_TOP + 2.55, w: leftW, h: CONTENT_H - 2.55, title: "About This University", items: u.keyFacts.slice(0, 4) });
    }

    // Right: abstract location card -- purely decorative concentric-circle
    // marker + city/country text, never a real map (plan item 16).
    const rightX = MARGIN + leftW + GUTTER;
    const rightW = PAGE_W - MARGIN - rightX;
    slide.addShape("roundRect", { x: rightX, y: CONTENT_TOP, w: rightW, h: CONTENT_H, rectRadius: RADIUS_CARD, fill: { color: COLORS.purpleDeep } });
    slide.addText("LOCATION", { x: rightX, y: CONTENT_TOP + 0.35, w: rightW, h: 0.3, fontSize: 11, bold: true, color: COLORS.gold, align: "center", charSpacing: 2, fontFace: FONT });
    const pinCx = rightX + rightW / 2;
    const pinCy = CONTENT_TOP + CONTENT_H / 2 - 0.3;
    slide.addShape("ellipse", { x: pinCx - 0.6, y: pinCy - 0.6, w: 1.2, h: 1.2, fill: { color: "4A2F55" } });
    slide.addShape("ellipse", { x: pinCx - 0.3, y: pinCy - 0.3, w: 0.6, h: 0.6, fill: { color: COLORS.gold } });
    if (u.city) slide.addText(u.city.toUpperCase(), { x: rightX + 0.3, y: pinCy + 0.85, w: rightW - 0.6, h: 0.45, fontSize: 20, bold: true, color: COLORS.white, align: "center", fontFace: FONT });
    if (u.country) slide.addText(u.country.toUpperCase(), { x: rightX + 0.3, y: pinCy + 1.3, w: rightW - 0.6, h: 0.3, fontSize: 12, color: COLORS.rose, align: "center", charSpacing: 1, fontFace: FONT });

    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Finding the Right Home ----
function buildResidencesSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Housing", title: "Finding the Right Home" });
    const cardW = (CONTENT_W - GUTTER * 2) / 3;
    n.residences.forEach((r, i) => {
        const x = MARGIN + i * (cardW + GUTTER);
        const y = CONTENT_TOP;
        const h = CONTENT_H;
        slide.addShape("roundRect", { x, y, w: cardW, h, rectRadius: RADIUS_CARD, fill: { color: COLORS.white }, line: CARD_LINE });
        const pad = 0.24;

        DS.numberBadge(slide, { x: x + pad, y: y + pad, d: 0.38, text: i + 1, fontSize: 13 });
        if (r.badge) DS.pill(slide, { x: x + cardW - pad - 1.7, y: y + pad, w: 1.7, h: 0.32, text: r.badge, fill: COLORS.rose, fontSize: 9 });

        slide.addText(truncate(r.name, 50), { x: x + pad, y: y + pad + 0.56, w: cardW - pad * 2, h: 0.7, fontSize: TYPE.cardTitle, bold: true, color: COLORS.ink, fontFace: FONT, valign: "top" });
        if (r.roomType) slide.addText(r.roomType, { x: x + pad, y: y + pad + 1.28, w: cardW - pad * 2, h: 0.3, fontSize: 12, color: COLORS.inkFaint, fontFace: FONT });

        // Price dominates -- large amount, small "/duration" suffix.
        const [amountPart, durationPart] = (r.price || "").split("/");
        if (amountPart) {
            slide.addText(
                [{ text: amountPart, options: { fontSize: 30, bold: true, color: COLORS.purple } }, durationPart ? { text: `/${durationPart}`, options: { fontSize: 13, color: COLORS.inkFaint } } : null].filter(Boolean),
                { x: x + pad, y: y + h - 1.55, w: cardW - pad * 2, h: 0.55, fontFace: FONT, valign: "bottom" }
            );
        }
        const meta = [Number.isFinite(r.distanceKm) ? `${r.distanceKm} km` : null, Number.isFinite(r.walkingMinutes) ? `${r.walkingMinutes} min walk` : null, Number.isFinite(r.rating) ? `${r.rating} / 5` : null].filter(Boolean);
        if (meta.length > 0) {
            slide.addText(meta.join("   ·   "), { x: x + pad, y: y + h - 0.75, w: cardW - pad * 2, h: 0.4, fontSize: 11.5, color: COLORS.inkSoft, fontFace: FONT });
        }
    });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Residence Comparison ----
function buildComparisonSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Housing", title: "Residence Comparison" });
    const cols = [
        { key: "name", label: "Residence", w: 4.4, align: "left" },
        { key: "distanceKm", label: "Distance", w: 1.7, align: "left" },
        { key: "price", label: "Price", w: 2.0, align: "left" },
        { key: "rating", label: "Rating", w: 1.6, align: "left" },
        { key: "matchScore", label: "Match", w: 2.433, align: "left" },
    ];
    const colX = [];
    let cx = MARGIN;
    cols.forEach((c) => { colX.push(cx); cx += c.w; });

    const headerH = 0.46;
    const rowH = 0.6;
    slide.addShape("roundRect", { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: headerH, rectRadius: 0.06, fill: { color: COLORS.purple } });
    cols.forEach((c, i) => {
        slide.addText(c.label.toUpperCase(), { x: colX[i] + 0.18, y: CONTENT_TOP, w: c.w - 0.3, h: headerH, fontSize: TYPE.sectionLabel, bold: true, color: COLORS.goldLight, valign: "middle", charSpacing: 1, fontFace: FONT });
    });

    n.comparison.forEach((r, i) => {
        const y = CONTENT_TOP + headerH + i * rowH;
        const isTop = i === 0;
        slide.addShape("rect", { x: MARGIN, y, w: CONTENT_W, h: rowH, fill: { color: isTop ? "F3E7EE" : (i % 2 === 0 ? COLORS.white : COLORS.surface) } });
        if (isTop) slide.addShape("rect", { x: MARGIN, y, w: 0.06, h: rowH, fill: { color: COLORS.gold } });

        slide.addText(truncate(r.name, 42), { x: colX[0] + 0.18, y, w: cols[0].w - 0.3, h: rowH, fontSize: TYPE.table, bold: true, color: COLORS.ink, valign: "middle", fontFace: FONT });
        slide.addText(Number.isFinite(r.distanceKm) ? `${r.distanceKm} km` : "--", { x: colX[1] + 0.18, y, w: cols[1].w - 0.3, h: rowH, fontSize: TYPE.table, color: COLORS.inkSoft, valign: "middle", fontFace: FONT });
        slide.addText(r.price || "--", { x: colX[2] + 0.18, y, w: cols[2].w - 0.3, h: rowH, fontSize: TYPE.table, color: COLORS.inkSoft, valign: "middle", fontFace: FONT });
        slide.addText(Number.isFinite(r.rating) ? `${r.rating} / 5` : "--", { x: colX[3] + 0.18, y, w: cols[3].w - 0.3, h: rowH, fontSize: TYPE.table, color: COLORS.inkSoft, valign: "middle", fontFace: FONT });

        if (Number.isFinite(r.matchScore)) {
            slide.addText(`${r.matchScore}%`, { x: colX[4] + 0.18, y: y + 0.05, w: cols[4].w - 0.3, h: 0.3, fontSize: TYPE.table, bold: true, color: COLORS.purple, fontFace: FONT });
            DS.progressBar(slide, { x: colX[4] + 0.18, y: y + rowH - 0.22, w: cols[4].w - 0.36, h: 0.1, value: r.matchScore });
        } else {
            slide.addText("--", { x: colX[4] + 0.18, y, w: cols[4].w - 0.3, h: rowH, fontSize: TYPE.table, color: COLORS.inkSoft, valign: "middle", fontFace: FONT });
        }
    });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Estimated Living Expenses ----
function buildLivingCostsSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Living Costs", title: "Estimated Living Expenses" });
    const le = n.livingExpenses;
    const leftW = 3.7;

    if (le.totalMonthly !== null) {
        DS.metricCard(slide, { x: MARGIN, y: CONTENT_TOP, w: leftW, h: 1.85, label: "Estimated / Month", value: `${le.currency}${le.totalMonthly.toLocaleString()}`, tone: "solid" });
    }
    if (le.totalAnnual !== null) {
        DS.metricCard(slide, { x: MARGIN, y: CONTENT_TOP + 2.05, w: leftW, h: 1.4, label: "Estimated / Year", value: `${le.currency}${le.totalAnnual.toLocaleString()}`, tone: "outline" });
    }

    const rightX = MARGIN + leftW + GUTTER;
    const rightW = PAGE_W - MARGIN - rightX;
    const maxValue = Math.max(1, ...le.rows.map((r) => r.value));
    const rowH = Math.min(0.72, CONTENT_H / Math.max(1, le.rows.length));
    le.rows.forEach((row, i) => {
        const y = CONTENT_TOP + i * rowH;
        slide.addText(row.label, { x: rightX, y, w: rightW * 0.5, h: 0.32, fontSize: TYPE.body, color: COLORS.inkSoft, fontFace: FONT });
        slide.addText(row.formatted, { x: rightX + rightW * 0.5, y, w: rightW * 0.5, h: 0.32, fontSize: TYPE.body, bold: true, color: COLORS.ink, align: "right", fontFace: FONT });
        DS.progressBar(slide, { x: rightX, y: y + 0.36, w: rightW, h: 0.12, value: row.value, max: maxValue });
    });

    if (le.note) slide.addText(le.note, { x: MARGIN, y: CONTENT_BOTTOM - 0.36, w: CONTENT_W, h: 0.3, fontSize: 9.5, italic: true, color: COLORS.inkFaint, fontFace: FONT });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Your Degree & Skills ----
function buildDegreeSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Degree", title: "Your Degree & Skills" });
    const d = n.degree;

    slide.addText(d.name, { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W - 2.4, h: 0.5, fontSize: 24, bold: true, color: COLORS.ink, fontFace: FONT });
    if (d.category) DS.pill(slide, { x: PAGE_W - MARGIN - 2.2, y: CONTENT_TOP + 0.06, w: 2.2, h: 0.36, text: d.category, fill: COLORS.rose, fontSize: 10 });
    if (d.summary) {
        slide.addText(truncate(d.summary, 230), { x: MARGIN, y: CONTENT_TOP + 0.56, w: CONTENT_W, h: 0.8, fontSize: TYPE.body, color: COLORS.inkSoft, fontFace: FONT, lineSpacingMultiple: 1.3, valign: "top" });
    }

    const colW = (CONTENT_W - GUTTER) / 2;
    const chipsY = CONTENT_TOP + 1.55;
    slide.addText("CORE SKILLS", { x: MARGIN, y: chipsY, w: colW, h: 0.28, fontSize: TYPE.sectionLabel, bold: true, color: COLORS.rose, charSpacing: 1, fontFace: FONT });
    DS.chipRow(slide, d.coreSkills, { x: MARGIN, y: chipsY + 0.34, w: colW });
    slide.addText("TECHNICAL AREAS", { x: MARGIN + colW + GUTTER, y: chipsY, w: colW, h: 0.28, fontSize: TYPE.sectionLabel, bold: true, color: COLORS.rose, charSpacing: 1, fontFace: FONT });
    DS.chipRow(slide, d.technicalAreas, { x: MARGIN + colW + GUTTER, y: chipsY + 0.34, w: colW, fill: COLORS.surface, textColor: COLORS.inkSoft });

    if (d.specialization) {
        const bandY = CONTENT_BOTTOM - 0.85;
        slide.addShape("roundRect", { x: MARGIN, y: bandY, w: CONTENT_W, h: 0.75, rectRadius: RADIUS_CARD, fill: { color: COLORS.purpleDeep } });
        // Label stays small-caps (it's a category tag); the specialization
        // NAME itself keeps its natural casing -- it's real data being
        // displayed, not a section label, and forcing it upper-case would
        // hurt legibility of a proper noun like "AI / Machine Learning".
        slide.addText(
            [
                { text: "SPECIALIZATION  ", options: { fontSize: 11, bold: true, color: COLORS.gold, charSpacing: 0.8 } },
                { text: d.specialization.name, options: { fontSize: 15, bold: true, color: COLORS.white } },
            ],
            { x: MARGIN + 0.24, y: bandY + 0.12, w: CONTENT_W - 0.48, h: 0.32, fontFace: FONT, valign: "middle" }
        );
        slide.addText(d.specialization.emphasisSkills.join("   ·   "), { x: MARGIN + 0.24, y: bandY + 0.44, w: CONTENT_W - 0.48, h: 0.28, fontSize: 12, color: "D9C4E0", fontFace: FONT });
    }
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Career Paths From Your Degree ----
function buildCareersSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Career", title: "Career Paths From Your Degree" });
    const [hero, ...rest] = n.careers;
    const heroH = 1.7;

    // Hero card -- the top-ranked career visually dominates the slide.
    slide.addShape("roundRect", { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: heroH, rectRadius: RADIUS_CARD, fill: { color: COLORS.purple } });
    DS.numberBadge(slide, { x: MARGIN + 0.26, y: CONTENT_TOP + 0.26, d: 0.5, text: 1, fill: COLORS.gold, textColor: COLORS.purpleDeep, fontSize: 18 });
    slide.addText(hero.title, { x: MARGIN + 1.0, y: CONTENT_TOP + 0.2, w: 7.5, h: 0.42, fontSize: 21, bold: true, color: COLORS.white, fontFace: FONT });
    if (hero.matchLabel) {
        slide.addText(hero.matchLabel.toUpperCase(), { x: MARGIN + 1.0, y: CONTENT_TOP + 0.62, w: 4, h: 0.28, fontSize: 11, bold: true, color: COLORS.goldLight, charSpacing: 1, fontFace: FONT });
        qualitativeBar(slide, { x: MARGIN + 1.0, y: CONTENT_TOP + 0.9, w: 2.6, value: hero.matchLabel === "Strong Match" ? 3 : hero.matchLabel === "Good Match" ? 2 : 1 });
    }
    if (hero.summary) slide.addText(truncate(hero.summary, 130), { x: MARGIN + 1.0, y: CONTENT_TOP + 1.1, w: CONTENT_W - 1.3, h: 0.36, fontSize: 12, color: "E3D3E8", fontFace: FONT });
    const heroSkillLine = [hero.alreadyHaveSkills.length ? `Covered: ${hero.alreadyHaveSkills.slice(0, 3).join(", ")}` : "", hero.skillsToDevelop.length ? `Develop: ${hero.skillsToDevelop.slice(0, 3).join(", ")}` : ""].filter(Boolean).join("     ");
    if (heroSkillLine) slide.addText(heroSkillLine, { x: MARGIN + 1.0, y: CONTENT_TOP + heroH - 0.36, w: CONTENT_W - 1.3, h: 0.3, fontSize: 10.5, color: COLORS.goldLight, fontFace: FONT });

    const restTop = CONTENT_TOP + heroH + 0.18;
    const restH = CONTENT_BOTTOM - restTop;
    const rowH = rest.length ? Math.min(0.72, (restH - (rest.length - 1) * 0.1) / rest.length) : 0;
    rest.forEach((career, i) => {
        const y = restTop + i * (rowH + 0.1);
        slide.addShape("roundRect", { x: MARGIN, y, w: CONTENT_W, h: rowH, rectRadius: 0.06, fill: { color: COLORS.white }, line: CARD_LINE });
        DS.numberBadge(slide, { x: MARGIN + 0.16, y: y + rowH / 2 - 0.15, d: 0.3, text: i + 2, fontSize: 11, fill: COLORS.rose });
        slide.addText(career.title, { x: MARGIN + 0.6, y: y + 0.06, w: 4.2, h: 0.3, fontSize: 14, bold: true, color: COLORS.ink, fontFace: FONT });
        if (career.matchLabel) DS.pill(slide, { x: MARGIN + 4.9, y: y + rowH / 2 - 0.15, w: 1.7, h: 0.3, text: career.matchLabel, fill: matchTone(career.matchLabel).fill, fontSize: 9 });
        const skillLine = [career.alreadyHaveSkills.length ? `Covered: ${career.alreadyHaveSkills.slice(0, 2).join(", ")}` : "", career.skillsToDevelop.length ? `Develop: ${career.skillsToDevelop.slice(0, 2).join(", ")}` : ""].filter(Boolean).join("   ");
        if (skillLine) slide.addText(skillLine, { x: MARGIN + 6.8, y: y + rowH / 2 - 0.16, w: CONTENT_W - 6.8 - 0.2, h: 0.32, fontSize: 10, color: COLORS.inkFaint, align: "right", valign: "middle", fontFace: FONT });
    });

    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Estimated Salary Progression ----
function buildSalarySlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Salary", title: "Estimated Salary Progression" });
    slide.addText(n.primaryCareerTitle || "Your top career match", { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: 0.4, fontSize: 18, bold: true, color: COLORS.ink, fontFace: FONT });
    if (n.salary.country) slide.addText(`Estimated salary in ${n.salary.country}`, { x: MARGIN, y: CONTENT_TOP + 0.42, w: CONTENT_W, h: 0.3, fontSize: 12.5, color: COLORS.rose, fontFace: FONT });

    const stages = n.salary.stages;
    const rowY = CONTENT_TOP + 1.3;
    const nodeD = 0.5;
    const slotW = CONTENT_W / stages.length;
    slide.addShape("line", { x: MARGIN, y: rowY + nodeD / 2, w: CONTENT_W, h: 0, line: { color: COLORS.border, width: 2 } });
    stages.forEach((stage, i) => {
        const isLast = i === stages.length - 1;
        const cx = MARGIN + slotW * i + slotW / 2 - nodeD / 2;
        slide.addShape("ellipse", { x: cx, y: rowY, w: nodeD, h: nodeD, fill: { color: isLast ? COLORS.gold : COLORS.purple } });
        slide.addText(String(i + 1), { x: cx, y: rowY, w: nodeD, h: nodeD, fontSize: 15, bold: true, color: COLORS.white, align: "center", valign: "middle", fontFace: FONT });
        slide.addText(stage.label.toUpperCase(), { x: MARGIN + slotW * i, y: rowY - 0.4, w: slotW, h: 0.3, fontSize: 11, bold: true, color: COLORS.inkFaint, align: "center", charSpacing: 0.8, fontFace: FONT });
        slide.addText(stage.value, { x: MARGIN + slotW * i, y: rowY + nodeD + 0.16, w: slotW, h: 0.55, fontSize: isLast ? 25 : 21, bold: true, color: isLast ? COLORS.gold : COLORS.purple, align: "center", fontFace: FONT });
    });

    slide.addText(n.salary.note, { x: MARGIN, y: CONTENT_BOTTOM - 0.62, w: CONTENT_W, h: 0.5, fontSize: 10.5, italic: true, color: COLORS.inkFaint, fontFace: FONT, lineSpacingMultiple: 1.3 });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Your Hiring Path ----
function buildHiringPathSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Hiring", title: "Your Hiring Path" });
    slide.addText(`For your strongest match: ${n.primaryCareerTitle || ""}`, { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: 0.32, fontSize: 12.5, bold: true, color: COLORS.rose, fontFace: FONT });

    const gridTop = CONTENT_TOP + 0.42;
    const colW = (CONTENT_W - GUTTER) / 2;
    const rowH = (CONTENT_BOTTOM - gridTop - GUTTER) / 2;
    const interviewItems = n.readiness.interviewAreas.flatMap((group) => group.items.slice(0, 2).map((item) => `${group.label}: ${item}`)).slice(0, 5);
    const quadrants = [
        { num: "01", title: "Skills to Develop", items: n.readiness.skillsToDevelop },
        { num: "02", title: "Portfolio Evidence", items: n.readiness.projectEvidence.length > 0 ? n.readiness.projectEvidence : n.readiness.portfolioExpectations },
        { num: "03", title: "Interview Preparation", items: interviewItems },
        { num: "04", title: "Typical Entry Routes", items: n.readiness.entryRoutes },
    ];
    quadrants.forEach((q, i) => {
        const col = i % 2;
        const row = Math.floor(i / 2);
        const x = MARGIN + col * (colW + GUTTER);
        const y = gridTop + row * (rowH + GUTTER);
        slide.addShape("roundRect", { x, y, w: colW, h: rowH, rectRadius: RADIUS_CARD, fill: { color: COLORS.white }, line: CARD_LINE });
        slide.addText(q.num, { x: x + colW - 0.9, y: y + 0.1, w: 0.75, h: 0.5, fontSize: 26, bold: true, color: COLORS.track, align: "right", fontFace: FONT });
        slide.addText(q.title.toUpperCase(), { x: x + 0.24, y: y + 0.2, w: colW - 1.1, h: 0.3, fontSize: TYPE.sectionLabel, bold: true, color: COLORS.purple, charSpacing: 1, fontFace: FONT });
        slide.addText(
            q.items.slice(0, 5).map((item) => ({ text: item, options: { bullet: { code: "2022", color: COLORS.rose }, breakLine: true } })),
            { x: x + 0.24, y: y + 0.56, w: colW - 0.48, h: rowH - 0.72, fontSize: 12.5, color: COLORS.inkSoft, fontFace: FONT, valign: "top", lineSpacingMultiple: 1.28 }
        );
    });

    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Suggested Preparation Path ----
function buildPreparationSlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "Hiring", title: "Suggested Preparation Path" });
    slide.addText("An indicative sequence -- not a required or guaranteed path.", { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: 0.3, fontSize: 11.5, italic: true, color: COLORS.inkFaint, fontFace: FONT });

    const steps = n.readiness.preparationSteps;
    const rowY = CONTENT_TOP + 1.0;
    const nodeD = 0.48;
    const slotW = CONTENT_W / steps.length;
    slide.addShape("line", { x: MARGIN, y: rowY + nodeD / 2, w: CONTENT_W, h: 0, line: { color: COLORS.border, width: 2 } });
    steps.forEach((step, i) => {
        const cx = MARGIN + slotW * i + slotW / 2 - nodeD / 2;
        slide.addShape("ellipse", { x: cx, y: rowY, w: nodeD, h: nodeD, fill: { color: COLORS.purple } });
        slide.addText(String(i + 1), { x: cx, y: rowY, w: nodeD, h: nodeD, fontSize: 14, bold: true, color: COLORS.white, align: "center", valign: "middle", fontFace: FONT });
        slide.addText(truncate(step, 90), {
            x: MARGIN + slotW * i + 0.05, y: rowY + nodeD + 0.14, w: slotW - 0.1, h: CONTENT_BOTTOM - (rowY + nodeD + 0.14),
            fontSize: 11.5, color: COLORS.inkSoft, align: "center", fontFace: FONT, valign: "top", lineSpacingMultiple: 1.2,
        });
    });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: From Housing to Hiring (journey centerpiece) ----
function buildJourneySlide(pptx, n, pageNum, totalPages) {
    const { slide } = DS.frame(pptx, { sectionLabel: "The IVYHUTS Concept", title: "From Housing to Hiring" });
    slide.addText(
        "One plan connecting where you live, what you study and where your career can go.",
        { x: MARGIN, y: CONTENT_TOP, w: CONTENT_W, h: 0.35, fontSize: 13, color: COLORS.inkSoft, fontFace: FONT }
    );
    DS.journeyChain(slide, n.journeySteps, { x: MARGIN, y: CONTENT_TOP + 1.2, w: CONTENT_W, nodeD: 0.8, fontSize: 11.5 });
    DS.footer(slide, pageNum, totalPages);
    return slide;
}

// ---- Slide: Closing / Your Next Move ----
function buildClosingSlide(pptx, n, pageNum, totalPages) {
    const slide = pptx.addSlide();
    slide.background = { color: COLORS.purpleDeep };
    const leftW = 5.4;

    slide.addText("YOUR NEXT MOVE", { x: MARGIN, y: 1.4, w: leftW, h: 0.32, fontSize: 12, bold: true, color: COLORS.gold, charSpacing: 2, fontFace: FONT });
    slide.addText("Turn your plan\ninto action.", { x: MARGIN, y: 1.85, w: leftW, h: 1.8, fontSize: 34, bold: true, color: COLORS.white, fontFace: FONT, lineSpacingMultiple: 1.08 });
    slide.addShape("line", { x: MARGIN, y: 3.85, w: 0.7, h: 0, line: { color: COLORS.gold, width: 3 } });

    const rightX = MARGIN + leftW + 0.6;
    const rightW = PAGE_W - MARGIN - rightX;
    const stepGap = Math.min(0.85, (5.6 - 1.35) / Math.max(1, n.closingSteps.length));
    n.closingSteps.forEach((step, i) => {
        const y = 1.5 + i * stepGap;
        DS.numberBadge(slide, { x: rightX, y, d: 0.42, text: i + 1, fill: COLORS.rose, textColor: COLORS.purpleDeep, fontSize: 14 });
        slide.addText(step, { x: rightX + 0.62, y: y + 0.02, w: rightW - 0.62, h: 0.5, fontSize: 15, color: COLORS.white, fontFace: FONT, valign: "middle" });
        if (i < n.closingSteps.length - 1) slide.addShape("line", { x: rightX + 0.21, y: y + 0.42, w: 0, h: stepGap - 0.42, line: { color: "6E4E7E", width: 1.5 } });
    });

    slide.addShape("line", { x: MARGIN, y: PAGE_H - 1.1, w: PAGE_W - MARGIN * 2, h: 0, line: { color: COLORS.gold, width: 1 } });
    slide.addText(
        [{ text: "IVY", options: { color: COLORS.white, bold: true } }, { text: "huts", options: { color: COLORS.goldLight, bold: true } }, { text: "   Housing to Hiring", options: { color: "C9B4C4", bold: false } }],
        { x: MARGIN, y: PAGE_H - 0.92, w: 8, h: 0.4, fontSize: 14, fontFace: FONT }
    );
    slide.addText(`${pageNum} / ${totalPages}`, { x: PAGE_W - MARGIN - 1.0, y: PAGE_H - 0.6, w: 1.0, h: 0.3, fontSize: 9, color: "9C82A0", align: "right", fontFace: FONT });
    return slide;
}

// Builds the full presentation from an already-normalized model
// (./pptNormalize.js's output -- untouched by this redesign). Conditional
// slides are simply omitted when their section's data isn't available --
// Cover, Journey and Closing always render.
function buildPresentation(normalized) {
    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.author = "IVYHUTS";
    pptx.company = "IVYHUTS";
    pptx.title = "IVYHUTS Student Plan";
    pptx.subject = "Housing to Hiring Student Plan";

    buildCoverSlide(pptx, normalized);

    const builders = [];
    if (normalized.university.available) builders.push(buildUniversitySlide);
    if (normalized.residences.length > 0) builders.push(buildResidencesSlide);
    if (normalized.comparison.length > 0) builders.push(buildComparisonSlide);
    if (normalized.livingExpenses.available) builders.push(buildLivingCostsSlide);
    if (normalized.degree.available) builders.push(buildDegreeSlide);
    if (normalized.careers.length > 0) builders.push(buildCareersSlide);
    if (normalized.salary.available) builders.push(buildSalarySlide);
    if (normalized.readiness.available) {
        builders.push(buildHiringPathSlide);
        if (normalized.readiness.preparationSteps.length > 0) builders.push(buildPreparationSlide);
    }
    builders.push(buildJourneySlide);
    builders.push(buildClosingSlide);

    const totalPages = 1 + builders.length; // +1 for the cover slide
    builders.forEach((build, i) => build(pptx, normalized, i + 2, totalPages));

    return pptx;
}

async function generateStudentPlanPptxBuffer(normalized) {
    const pptx = buildPresentation(normalized);
    const buffer = await pptx.write({ outputType: "nodebuffer" });
    return buffer;
}

module.exports = {
    generateStudentPlanPptxBuffer,
    buildPresentation,
    // Exposed for unit testing / structural inspection.
    PAGE_W,
    PAGE_H,
};
